/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Contract, Invocation, EstimateFeeResponse } from "starknet";
import type { BigNumberish } from "starknet/utils/number";
import type BN from "bn.js";
import type { BlockIdentifier } from "starknet/provider/utils";

export type Uint256 = { low: BigNumberish; high: BigNumberish };
export type Uint256Output = { low: BN; high: BN };

export interface BitMathTest__WC__BitMathTest_compiled extends Contract {
  mostSignificantBit_e6bcbc65(
    __warp_usrid0_x: Uint256,
    options?: { blockIdentifier?: BlockIdentifier }
  ): Promise<[BN] & { __warp_usrid1_r: BN }>;
  leastSignificantBit_d230d23f(
    __warp_usrid2_x: Uint256,
    options?: { blockIdentifier?: BlockIdentifier }
  ): Promise<[BN] & { __warp_usrid3_r: BN }>;
  functions: {
    mostSignificantBit_e6bcbc65(
      __warp_usrid0_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[BN] & { __warp_usrid1_r: BN }>;
    leastSignificantBit_d230d23f(
      __warp_usrid2_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[BN] & { __warp_usrid3_r: BN }>;
  };
  callStatic: {
    mostSignificantBit_e6bcbc65(
      __warp_usrid0_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[BN] & { __warp_usrid1_r: BN }>;
    leastSignificantBit_d230d23f(
      __warp_usrid2_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[BN] & { __warp_usrid3_r: BN }>;
  };
  populateTransaction: {
    mostSignificantBit_e6bcbc65(
      __warp_usrid0_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Invocation;
    leastSignificantBit_d230d23f(
      __warp_usrid2_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Invocation;
  };
  estimateFee: {
    mostSignificantBit_e6bcbc65(
      __warp_usrid0_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<EstimateFeeResponse>;
    leastSignificantBit_d230d23f(
      __warp_usrid2_x: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<EstimateFeeResponse>;
  };
}
