/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Contract, Invocation, EstimateFeeResponse } from "starknet";
import type { BigNumberish } from "starknet/utils/number";
import type BN from "bn.js";
import type { BlockIdentifier } from "starknet/provider/utils";

export type Uint256 = { low: BigNumberish; high: BigNumberish };
export type Uint256Output = { low: BN; high: BN };

export interface FullMathTest__WC__FullMathTest_compiled extends Contract {
  mulDiv_aa9a0912(
    __warp_usrid0_x: Uint256,
    __warp_usrid1_y: Uint256,
    __warp_usrid2_z: Uint256,
    options?: { blockIdentifier?: BlockIdentifier }
  ): Promise<[Uint256Output] & { __warp_usrid3_: Uint256Output }>;
  mulDivRoundingUp_0af8b27f(
    __warp_usrid4_x: Uint256,
    __warp_usrid5_y: Uint256,
    __warp_usrid6_z: Uint256,
    options?: { blockIdentifier?: BlockIdentifier }
  ): Promise<[Uint256Output] & { __warp_usrid7_: Uint256Output }>;
  functions: {
    mulDiv_aa9a0912(
      __warp_usrid0_x: Uint256,
      __warp_usrid1_y: Uint256,
      __warp_usrid2_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[Uint256Output] & { __warp_usrid3_: Uint256Output }>;
    mulDivRoundingUp_0af8b27f(
      __warp_usrid4_x: Uint256,
      __warp_usrid5_y: Uint256,
      __warp_usrid6_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[Uint256Output] & { __warp_usrid7_: Uint256Output }>;
  };
  callStatic: {
    mulDiv_aa9a0912(
      __warp_usrid0_x: Uint256,
      __warp_usrid1_y: Uint256,
      __warp_usrid2_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[Uint256Output] & { __warp_usrid3_: Uint256Output }>;
    mulDivRoundingUp_0af8b27f(
      __warp_usrid4_x: Uint256,
      __warp_usrid5_y: Uint256,
      __warp_usrid6_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[Uint256Output] & { __warp_usrid7_: Uint256Output }>;
  };
  populateTransaction: {
    mulDiv_aa9a0912(
      __warp_usrid0_x: Uint256,
      __warp_usrid1_y: Uint256,
      __warp_usrid2_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Invocation;
    mulDivRoundingUp_0af8b27f(
      __warp_usrid4_x: Uint256,
      __warp_usrid5_y: Uint256,
      __warp_usrid6_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Invocation;
  };
  estimateFee: {
    mulDiv_aa9a0912(
      __warp_usrid0_x: Uint256,
      __warp_usrid1_y: Uint256,
      __warp_usrid2_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<EstimateFeeResponse>;
    mulDivRoundingUp_0af8b27f(
      __warp_usrid4_x: Uint256,
      __warp_usrid5_y: Uint256,
      __warp_usrid6_z: Uint256,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<EstimateFeeResponse>;
  };
}
