/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Contract, Invocation, EstimateFeeResponse } from "starknet";
import type { BigNumberish } from "starknet/utils/number";
import type { BlockIdentifier } from "starknet/provider/utils";
import type BN from "bn.js";

export interface LiquidityMathTest__WC__LiquidityMathTest_compiled
  extends Contract {
  addDelta_402d44fb(
    __warp_usrid0_x: BigNumberish,
    __warp_usrid1_y: BigNumberish,
    options?: { blockIdentifier?: BlockIdentifier }
  ): Promise<[BN] & { __warp_usrid2_z: BN }>;
  functions: {
    addDelta_402d44fb(
      __warp_usrid0_x: BigNumberish,
      __warp_usrid1_y: BigNumberish,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[BN] & { __warp_usrid2_z: BN }>;
  };
  callStatic: {
    addDelta_402d44fb(
      __warp_usrid0_x: BigNumberish,
      __warp_usrid1_y: BigNumberish,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<[BN] & { __warp_usrid2_z: BN }>;
  };
  populateTransaction: {
    addDelta_402d44fb(
      __warp_usrid0_x: BigNumberish,
      __warp_usrid1_y: BigNumberish,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Invocation;
  };
  estimateFee: {
    addDelta_402d44fb(
      __warp_usrid0_x: BigNumberish,
      __warp_usrid1_y: BigNumberish,
      options?: { blockIdentifier?: BlockIdentifier }
    ): Promise<EstimateFeeResponse>;
  };
}
